import { StockProvider } from "@/context/StockContext";
import "./globals.css";

export const metadata = {
  title: "Stock market app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` w-full antialiased`}>
        <StockProvider>{children}</StockProvider>
      </body>
    </html>
  );
}
